### ISSUE TITLE
Driver always matching

### ISSUE THREAD

**Issue by Yui-Ezic** [yageorgiy/botman-vk-community-callback-driver#1]
In class VkCommunityCallbackDriver field payload will never be null, because constructor call method `buildPayload()` which fill this field. But in method hasMatchingEvent() you do next check
```
public function hasMatchingEvent() {
   if (!is_null($this->payload)) {
        //...
    }

    return false;
}
```
Due to the fact that the payload is never null, the method never returns false and always matches. This leads to inoperability of other drivers.

**Comment by yageorgiy** [comment]
Fixed in v.1.5.1.
Tested with the Telegram driver, worked fine for me.

**Comment by Yui-Ezic** [comment]
Thank u. Maybe because telegram matches first, but tinker didn't work for me.

**Comment by yageorgiy** [comment]
As I understand, tinker doesn't work properly on Windows-based systems (tried to run on Windows 10, got i/o error).
Personally tested on Ubuntu 20.04 LTS (Ubuntu for Windows 10 application) with driver enabled, works fine.

**Comment by Yui-Ezic** [comment]
> As I understand, tinker doesn't work properly on Windows-based systems (tried to run on Windows 10, got i/o error).
> Personally tested on Ubuntu 20.04 LTS (Ubuntu for Windows 10 application) with driver enabled, works fine.

Tinker started working after fix. Botman selects the first driver that matching. In my case VK driver has been matched first, but it didn't reach the tinker driver and it caused an error.
