### ISSUE TITLE
Different errors in markSeen() method

### ISSUE THREAD

**Issue by Yui-Ezic** [yageorgiy/botman-vk-community-callback-driver#2]
When adding a bot to a chat, I got the error in markSeen method() "VK API returned error when processing method 'messages.markAsRead': One of the parameters specified was missing or invalid: message_ids is undefined."

I found several errors in this method.

Firstly, `$matchingMessage->getPayload()->get("id")` returns nothing because payload is json like
```
{
    "type": "message_new",
    "object": {
        "message": {
            "date": <int>,
            "from_id": <int>,
            "id": <int>,
            ...
        }
}
```
 and id fields locate inside object.message. To get it we need to use `$matchingMessage->getPayload()->get("object")['message']['id']` .

Secondly, 'message_ids' fields is deprecated from version 5.80 (https://vk.com/dev/messages.markAsRead).
![Screenshot](https://user-images.githubusercontent.com/21062493/88468348-ba362080-ceea-11ea-89a6-510f59003718.png)
(It's funny, but this is not written in the English version of the documentation)

Third, I don't know how to make this method work in chat. Maybe because messages from chats are not stored for bots and their id is always equals to zero.

**Comment by yageorgiy** [comment]
Same thing. Tried to use both `start_message_id` and `mark_conversation_as_read` work in chat, but got no effect at all. `markAsRead` works only in chats created by the community, user-created conversations are ignored.
However, message ID fix and `start_message_id` replacement are implemented in the newer version.

**Comment by Yui-Ezic** [comment]
Thanks

**Comment by Yui-Ezic** [comment]
Replace `$matchingMessage->getPayload()->get("id")` to `$matchingMessage->getPayload()->get("object")['message']` was not the best solution, because message_edit and message_reply events have a different json schema and this method throws an undefined index exception.

**Comment by yageorgiy** [comment]
Fixed in v.1.6.
