### ISSUE TITLE
[BUG] Private variables in vendor/yageorgiy/botman-vk-community-callback-driver/src/VkCommunityCallbackDriver.php

### ISSUE THREAD

**Issue by hello-i-am-pavel** [yageorgiy/botman-vk-community-callback-driver#8]
Просьба изменить область видимости переменных класса с private на protected т.к. нужно переопределить две функции, что сделать невозможно. 
![image](https://user-images.githubusercontent.com/5941831/100517671-68a1e900-319d-11eb-9b2b-af306cc482f1.png)

**Comment by yageorgiy** [comment]
Подправил. 
yageorgiy/botman-vk-community-callback-driver@b6cd105f6e5a2ddd173a840cfe22805f59d6bb8b
